# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 676)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 676))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 676))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
"    background: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 590, 380, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background: #F73736;\n"
"    color: white;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background: #DB0909;\n"
"    padding-left:-3px;\n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background:#970606;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 530, 930, 31))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    color: #06B025;\n"
"    font-size: 17px;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 1000, 400))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background: black;\n"
"    color: #ACFF59;\n"
"    font-size: 17px;\n"
"    border-radius:20px;\n"
"    border: 4px solid #D50909;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(810, 590, 141, 51))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    background: #F73736;\n"
"    color: white;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background: #DB0909;\n"
"    padding-left:-3px;\n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background:#970606;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 981, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    color: #06B025;\n"
"    font-size: 17px;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 590, 370, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    background: #F73736;\n"
"    color: white;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background: #DB0909;\n"
"    padding-left:-3px;\n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background:#970606;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 0, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    color: #06B025;\n"
"    font-size: 19px;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    font-size: 23px;\n"
"    color: #F73736;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 7, 70, 30))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    background: #F73736;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background: #DB0909;\n"
"    padding-left:-3px;\n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background:#970606;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(810, 10, 208, 50))
        self.widget.setStyleSheet("background-image: url(:/source/AKT_logo.png);")
        self.widget.setObjectName("widget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(730, 50, 73, 22))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"    background: #F73736;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"    border-radius: 5px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 50, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    color: #9D0B0F;\n"
"    font-size: 17px;\n"
"    font-family: \"Yu Gothic UI Semibold\";\n"
"}")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AKT DIV.5 見積管理ツール (V1.4版)"))
        self.pushButton.setText(_translate("MainWindow", "案件一覧表出力"))
        self.pushButton_2.setText(_translate("MainWindow", "閉じる"))
        self.label.setText(_translate("MainWindow", "Excelファイルをインポートしてください..."))
        self.pushButton_3.setText(_translate("MainWindow", "Excelインポート"))
        self.label_2.setText(_translate("MainWindow", "AKT DIV.5 見積管理ツール (V1.4版)"))
        self.pushButton_4.setText(_translate("MainWindow", "アバウト"))
        self.label_3.setText(_translate("MainWindow", "年度"))

import ui.Logo_AKT_rc
